#!/usr/bin/env python3

from galactic_demo import TrajectoryActionClient

import rclpy
from rclpy.executors import MultiThreadedExecutor


def main(args=None):
    rclpy.init(args=args)
    executor = MultiThreadedExecutor(num_threads=4)
    node = TrajectoryActionClient()
    executor.add_node(node)
    executor.spin()


if __name__ == '__main__':
    main()
