# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  - head_cloud
head_cloud:
    filtered_cloud_topic: /realsense/depth/color/points/filtered
    max_range: 1.2
    max_update_rate: 0.1
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /realsense/depth/color/points # this is pointed to a empty topic to disable it
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
octomap_resolution: 0.03
# robot_description_planning/shape_transform_cache_lookup_wait_time: 0
